let HIPPO_OWNER = process.env.PUBLIC_HIPPO_OWNER;
let HIPPO_GUEST_REACT = process.env.PUBLIC_HIPPO_GUEST_REACT;

let SERVER_URL_GUEST_NODE = process.env.PUBLIC_SERVER_URL_GUEST_NODE;
let PUBLIC_SERVER_URL_NOTIFICATIONS =
  process.env.PUBLIC_SERVER_URL_NOTIFICATIONS;

export {
  HIPPO_OWNER,
  HIPPO_GUEST_REACT,
  SERVER_URL_GUEST_NODE,
  PUBLIC_SERVER_URL_NOTIFICATIONS,
};
